import { listFields } from "@/lib/data/fields";
import { NewArchiveItemForm } from "./NewArchiveItemForm";

// Server actions on this page run AI calls (e.g. transcription) that can outlast the platform's default timeout.
export const maxDuration = 300;

export default async function NewArchiveItemPage({
  params,
}: {
  params: Promise<{ projectId: string }>;
}) {
  const { projectId } = await params;
  const fields = await listFields(projectId);
  const manualFields = fields.filter((f) => f.input_type === "manual");
  const automatedFields = fields.filter((f) => f.input_type === "automated");

  return (
    <div>
      <h2 className="mb-1 font-sans text-base font-extrabold">New archive record</h2>
      <p className="mb-6 max-w-2xl text-sm text-charcoal/60">
        Upload a file and fill in what you know. The fields on the right are
        generated by AI from what you enter on the left — review and edit them
        before saving.
      </p>
      <NewArchiveItemForm
        projectId={projectId}
        manualFields={manualFields}
        automatedFields={automatedFields}
      />
    </div>
  );
}
