import { listFields } from "@/lib/data/fields";
import { FormBuilderList } from "./FormBuilderList";

export default async function FormBuilderPage({
  params,
}: {
  params: Promise<{ projectId: string }>;
}) {
  const { projectId } = await params;
  const fields = await listFields(projectId);

  return (
    <div className="max-w-3xl">
      <h2 className="mb-1 font-sans text-base font-extrabold">Form Builder</h2>
      <p className="mb-6 max-w-2xl text-sm text-charcoal/60">
        Define the fields that make up an Archive record for this project. Manual
        fields are filled in by hand; automated fields are generated by AI from
        another field&rsquo;s content plus a prompt you write.
      </p>

      <FormBuilderList projectId={projectId} fields={fields} />
    </div>
  );
}
